server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: kindle-studio-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:54322/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false
    # locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

